### ISSUE TITLE
Publish old uploaded apps get ordered by upload date

### ISSUE THREAD

**Issue by cibersheep** [UbuntuOpenStore/openstore-meta#166]
1. Upload an app on date dd.mm.yyyy
2. Wait until it's a proper time to publish: on dd+5.mm.yyyy
3. App it's published under dd.mm.yyy

Expected behaviour:
app to be ordered by date dd+5.mm.yyyy

**Comment by bhdouglass** [comment]
I just pushed a fix for this, let me know if you notice anything else weird with it!

**Comment by cibersheep** [comment]
Nice. I think is working good but only as an «updated app» but it's not listed as «new app»...

**Comment by cibersheep** [comment]
Last available gets the date right but «published» still get the date wixh the app was uploaded

`
![screenshot20180103_191849077](https://user-images.githubusercontent.com/6640041/34533571-19f7e4e2-f0bb-11e7-9b85-5ad870ee7f3f.png)
`

**Comment by cibersheep** [comment]
I did upload the app before the fix and published it after the fix.
Do you want me to try with a new upload?

This is the app in question
https://open.uappexplorer.com/app/aenaairports.cibersheep

**Comment by bhdouglass** [comment]
Yeah feel free to test it with a new upload. Anything uploaded before the fix will already have a published date. Now with the fix you won't get a published date until after you actually publish it.
