### ISSUE TITLE
[xenial] 8192 app says it needs to be updated again and again

### ISSUE THREAD

**Issue by advocatux** [UbuntuOpenStore/openstore-meta#203]
- BQ E4.5 (krillin) running Ubuntu 16.04 (r91)
- OpenStore version: 2.40

OpenStore app says there's an update available for 8192 app but, after updating that app, OpenStore still states an update is available.

_application-click-openstore.openstore-team_openstore_2.40.log_ output http://paste.ubuntu.com/p/5GNCD8jKr9/

**Comment by bhdouglass** [comment]
Ok, I believe I've fixed the 8192 app for xenial and I've also fixed the underlying issue so it shouldn't happen again.

**Comment by bhdouglass** [comment]
Let me know if you are still having issues with this!

**Comment by advocatux** [comment]
Vivid version is fine (0.6) but xenial downloads version 0.5, so the issue is still there.

**Comment by bhdouglass** [comment]
As discussed on telegram this issue has been resolved
